title: Artesia Kabore # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello from Colorado! I'm a stay at home mom who rediscovered a passion for evidence and processes, leading me to pivot into data analytics. 
  My bachelors degree in Mathematics and current volunteer treasurer role has driven my expertise in analyzing financial data to guide business decisions. 
  <br><br>
  <a href="https://www.linkedin.com/in/artesiakabore/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
